# Generated by Django 3.0.5 on 2020-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('Flute_type', models.TextField()),
                ('Description', models.CharField(max_length=500)),
                ('Youtube_link', models.CharField(max_length=50)),
                ('lenght', models.CharField(max_length=20)),
                ('Materail', models.CharField(max_length=20)),
            ],
        ),
    ]
