# Generated by Django 3.0.5 on 2020-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='video_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
